// Generates the Ed25519 signing keypair.
// Private key: printed once as a single line for the TWINLAB_SIGNING_KEY env
// var. It is never written to disk. Public key: written to
// src/data/publicKey.ts so the client and /api/keys/public can serve it.
import { generateKeyPairSync } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const { publicKey, privateKey } = generateKeyPairSync("ed25519");

const privPem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();
const pubPem = publicKey.export({ type: "spki", format: "pem" }).toString();

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const target = join(root, "src", "data", "publicKey.ts");
writeFileSync(
  target,
  `// Generated by scripts/generate-keypair.mjs. Safe to commit; this is the\n// PUBLIC half of the signing keypair.\nexport const PUBLIC_KEY_PEM: string | null = ${JSON.stringify(pubPem)};\n`
);

console.log("Public key written to src/data/publicKey.ts");
console.log("");
console.log("Set this as TWINLAB_SIGNING_KEY (single line, \\n escaped):");
console.log("");
console.log(JSON.stringify(privPem).slice(1, -1));
console.log("");
console.log("Rotation: rerun this script, redeploy with the new env var, and");
console.log("keep the old public key available until every issued token expires.");
